name:                pst-hs

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pst-hs#readme>

dependencies:
- base >= 4.7 && < 5
- base
- webdriver
- process
- string-interpolate
- text
- numeric-prelude

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

# needed in order for haddock to generate docs for test deps
library:
  source-dirs: test

tests:
  pst-hs-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webdriver
    - process
    - string-interpolate
    - text
    - numeric-prelude

